### ISSUE TITLE
error: UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by morantr** [znck/grammarly#218]
Grammarly stopped working for me. It worked fine a few weeks ago.
I'm getting this error on the output log:
```
(node:6916) UnhandledPromiseRejectionWarning: Error: Socket connection failed: NOT_AUTHORIZED
    at GrammarlyClient._connect (/home/mshoegx/.vscode-server/extensions/znck.grammarly-0.14.0/dist/server/index.js:38903:19)
    at GrammarlyClient._queueOrSend (/home/mshoegx/.vscode-server/extensions/znck.grammarly-0.14.0/dist/server/index.js:38978:18)
    at /home/mshoegx/.vscode-server/extensions/znck.grammarly-0.14.0/dist/server/index.js:38876:18
    at new Promise (<anonymous>)
    at GrammarlyClient.send (/home/mshoegx/.vscode-server/extensions/znck.grammarly-0.14.0/dist/server/index.js:38874:16)
    at GrammarlyClient.sendWithErrorHandling (/home/mshoegx/.vscode-server/extensions/znck.grammarly-0.14.0/dist/server/index.js:39102:31)
    at GrammarlyClient.submitOT (/home/mshoegx/.vscode-server/extensions/znck.grammarly-0.14.0/dist/server/index.js:39194:21)
    at TextGrammarCheckHost.sync (/home/mshoegx/.vscode-server/extensions/znck.grammarly-0.14.0/dist/server/index.js:39943:24)
    at TextGrammarCheckHost.setText (/home/mshoegx/.vscode-server/extensions/znck.grammarly-0.14.0/dist/server/index.js:39886:19)
    at Function.update (/home/mshoegx/.vscode-server/extensions/znck.grammarly-0.14.0/dist/server/index.js:39686:28)
(node:6916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
1637054685723 DEBUG  [TextGrammarCheckHost] (66696c) Hosting file:///home/mshoegx/COMMIT_EDITMSG
```

Any idea what could be the problem?

**Comment by alTaWBC** [comment]
Is there any updated on this?

**Comment by learn2free** [comment]
same problem

**Comment by niladi** [comment]
+1

**Comment by IEvangelist** [comment]
Same here, I think something is broken. Perhaps the API has changed?

**Comment by morantr** [comment]
> @IEvangelist try use this workaround [#183 (comment)](https://github.com/znck/grammarly/issues/183#issuecomment-879557150)

Thanks that worked!

**Comment by znck** [comment]
Stale after #232
