### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by saurabhchandrapatel** [znck/grammarly#229]
(node:26408) UnhandledPromiseRejectionWarning: Error: Socket connection failed: SHUTDOWN
    at GrammarlyClient._connect (c:\Users\qktb6361\.vscode\extensions\znck.grammarly-0.14.0\dist\server\index.js:38903:19)
    at GrammarlyClient._queueOrSend (c:\Users\qktb6361\.vscode\extensions\znck.grammarly-0.14.0\dist\server\index.js:38978:18)
    at c:\Users\qktb6361\.vscode\extensions\znck.grammarly-0.14.0\dist\server\index.js:38876:18
    at new Promise (<anonymous>)
    at GrammarlyClient.send (c:\Users\qktb6361\.vscode\extensions\znck.grammarly-0.14.0\dist\server\index.js:38874:16)
    at GrammarlyClient.sendWithErrorHandling (c:\Users\qktb6361\.vscode\extensions\znck.grammarly-0.14.0\dist\server\index.js:39102:31)
    at GrammarlyClient.sendFeedbackForAlert (c:\Users\qktb6361\.vscode\extensions\znck.grammarly-0.14.0\dist\server\index.js:39197:21)
    at TextGrammarCheckHost.acceptAlert (c:\Users\qktb6361\.vscode\extensions\znck.grammarly-0.14.0\dist\server\index.js:39967:24)
    at c:\Users\qktb6361\.vscode\extensions\znck.grammarly-0.14.0\dist\server\index.js:40229:31
    at handleRequest (c:\Users\qktb6361\.vscode\extensions\znck.grammarly-0.14.0\dist\server\index.js:28494:27)
(node:26408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 141)
[Error - 2:09:50 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 2:09:55 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 2:09:59 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 2:10:02 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 2:10:06 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 2:10:27 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 2:10:37 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 2:10:39 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'length' of undefined
  Code: -32603

**Comment by peiranxiao** [comment]
same issue here.

**Comment by znck** [comment]
Stale after #232
