### ISSUE TITLE
Error while launching the language server outside of VSCode

### ISSUE THREAD

**Issue by jcs090218** [znck/grammarly#250]
Thanks for the quick fix in #248! ❤️ 

The language server started correctly if you installed it with the `extension` VSCode. But if you launch without it; you will get the following error:

```
Error: Cannot find module 'node-fetch'
Require stack:
- c:\Users\xxx\AppData\Roaming\.emacs.d\.cache\lsp\npm\@emacs-grammarly\grammarly-languageserver\node_modules\@emacs-grammarly\grammarly-languageserver\dist\index.node.cjs
- c:\Users\xxx\AppData\Roaming\.emacs.d\.cache\lsp\npm\@emacs-grammarly\grammarly-languageserver\node_modules\@emacs-grammarly\grammarly-languageserver\bin\server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at getNodeFetch (c:\Users\xxx\AppData\Roaming\.emacs.d\.cache\lsp\npm\@emacs-grammarly\grammarly-languageserver\node_modules\@emacs-grammarly\grammarly-languageserver\dist\index.node.cjs:51:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async c:\Users\xxx\AppData\Roaming\.emacs.d\.cache\lsp\npm\@emacs-grammarly\grammarly-languageserver\node_modules\@emacs-grammarly\grammarly-languageserver\dist\index.node.cjs:40:64 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\xxx\\AppData\\Roaming\\.emacs.d\\.cache\\lsp\\npm\\@emacs-grammarly\\grammarly-languageserver\\node_modules\\@emacs-grammarly\\grammarly-languageserver\\dist\\index.node.cjs',
    'c:\\Users\\xxx\\AppData\\Roaming\\.emacs.d\\.cache\\lsp\\npm\\@emacs-grammarly\\grammarly-languageserver\\node_modules\\@emacs-grammarly\\grammarly-languageserver\\bin\\server.js'
  ]
}
```

The solution is to add `node-fetch` as a dependency to `packages/grammarly-languageserver/package.json`. See diff [here](https://github.com/emacs-grammarly/grammarly-language-server/commit/a14e4f78417f7169d05dc01ddc5dbeca6daa9e37).

@znck  WDYT? 😖

**Comment by znck** [comment]
Will add changes from diff.
