### ISSUE TITLE
Compile error on richtext-encoder

### ISSUE THREAD

**Issue by jcs090218** [znck/grammarly#257]
Hi, it's me again! 😅 

I have just merged upstream, and tried to run `pnpm run build`; then I got the following error:

```
> @ build C:\Users\xxx\workspace\_grammarly\grammarly-language-server
> rollup -c && node scripts/build-web-extension.mjs


packages\grammarly-languageclient\src\index.ts → packages/grammarly-languageclient/dist/index.d.ts...
created packages/grammarly-languageclient/dist/index.d.ts in 773ms

packages\grammarly-richtext-encoder\src\index.ts → packages/grammarly-richtext-encoder/dist/index.d.ts...
packages/grammarly-richtext-encoder/src/index.ts(30,16): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
packages/grammarly-richtext-encoder/src/index.ts(30,43): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
packages/grammarly-richtext-encoder/src/index.ts(31,11): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
packages/grammarly-richtext-encoder/src/index.ts(32,16): error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
packages/grammarly-richtext-encoder/src/index.ts(34,14): error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

[!] (plugin dts) Error: Failed to compile. Check the logs above.
packages/grammarly-richtext-encoder/src/index.ts
Error: Failed to compile. Check the logs above.
    at error (C:\Users\xxx\workspace\_grammarly\grammarly-language-server\node_modules\.pnpm\rollup@2.71.1\node_modules\rollup\dist\shared\rollup.js:198:30)
    at throwPluginError (C:\Users\xxx\workspace\_grammarly\grammarly-language-server\node_modules\.pnpm\rollup@2.71.1\node_modules\rollup\dist\shared\rollup.js:21902:12)
    at Object.error (C:\Users\xxx\workspace\_grammarly\grammarly-language-server\node_modules\.pnpm\rollup@2.71.1\node_modules\rollup\dist\shared\rollup.js:22625:20)
    at Object.error (C:\Users\xxx\workspace\_grammarly\grammarly-language-server\node_modules\.pnpm\rollup@2.71.1\node_modules\rollup\dist\shared\rollup.js:22079:42)
    at Object.transform (C:\Users\xxx\workspace\_grammarly\grammarly-language-server\node_modules\.pnpm\rollup-plugin-dts@3.0.2_ucrswzumipog3rfswkcvuves4u\node_modules\rollup-plugin-dts\dist\rollup-plugin-dts.cjs:1515:26)
    at C:\Users\xxx\workspace\_grammarly\grammarly-language-server\node_modules\.pnpm\rollup@2.71.1\node_modules\rollup\dist\shared\rollup.js:22834:37
```

Is this something related to updating bin? Thanks for the hard work as always! :)

**Comment by znck** [comment]
I had add a hack for unit test. What's your tsconfig? I think it's stricter than this project.

**Comment by jcs090218** [comment]
Sorry I'm not very familiar with the taconfig file. Which were you referring to?

Allow me to paste the downstream repo here, https://github.com/emacs-grammarly/grammarly-language-server.

I don't think I have changed any of those files.
