### ISSUE TITLE
Connection issue: UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by mikaelwallin-rw** [znck/grammarly#30]
This extension does not work for me at all. 
I have filled in grammarly.username and grammarly.password in settings.
Error message:
2020-02-24T07:49:37.149Z grammarly:host {
  type: 'INIT',
  documentId: 'file:///c%3A/XX.md',
  account: 'public'
}
(node:19612) UnhandledPromiseRejectionWarning: FetchError: request to https://www.grammarly.com/signin failed, reason: getaddrinfo ENOTFOUND www.grammarly.com
    at ClientRequest.<anonymous> (c:\Users\XX\.vscode\extensions\znck.grammarly-0.6.2\out\server.js:15380:11)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
(node:19612) UnhandledPromiseRejectionWarning: FetchError: request to https://www.grammarly.com/signin failed, reason: getaddrinfo ENOTFOUND www.grammarly.com
    at ClientRequest.<anonymous> (c:\Users\XX\.vscode\extensions\znck.grammarly-0.6.2\out\server.js:15380:11)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
(node:19612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:19612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)

**Comment by jagaSto** [comment]
Getting the same error, the extension has unfortunately not been working for the last two days. In addition to the above, I get an 401 for the authentification attempt

`grammarly:auth authentication failed 401 Headers`
