### ISSUE TITLE
Error: Cannot find module 'node:perf_hooks'

### ISSUE THREAD

**Issue by semaphore-egg** [znck/grammarly#301]
The latest version raises the following exceptions:
 
```
internal/modules/cjs/loader.js:937
  throw err;
  ^

Error: Cannot find module 'node:perf_hooks'
Require stack:
- /home/kd/.vscode/extensions/znck.grammarly-0.23.8/dist/server/index.node.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /home/kd/.vscode/extensions/znck.grammarly-0.23.8/dist/server/index.node.js:38:3661
    at /home/kd/.vscode/extensions/znck.grammarly-0.23.8/dist/server/index.node.js:2:245
    at Object.<anonymous> (/home/kd/.vscode/extensions/znck.grammarly-0.23.8/dist/server/index.node.js:64:604)
    at Module._compile (internal/modules/cjs/loader.js:1125:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/kd/.vscode/extensions/znck.grammarly-0.23.8/dist/server/index.node.js'
  ]
}
[Error - 10:04:36 PM] Connection to server got closed. Server will not be restarted.

```

version == v0.14.0 seems do not have such problems.

node version is:
```
> node -v
v16.14.0
> npm -v
8.3.1
```

**Comment by lacinoire** [comment]
I have the same problem in Version 0.22.1 on MacOS (Monterey, 12.4) with Node `v18.6.0` installed through brew

**Comment by jcs090218** [comment]
Duplicate of #264.

**Comment by semaphore-egg** [comment]
> Duplicate of #264.

Are there any solutions so far? It seems there is something wrong with the version `> 0.14`. Updating to the latest version does not solve the problem.

**Comment by twofingerrightclick** [comment]
using v0.22.1
I updated to vscode 1.70.2 from 1.70.1 and now the extension starts (no more perf error), but now getting issue a not found when logging in for the callback that tries to use the netlify function at  https://vscode-extension-grammarly.netlify.app/.netlify/functions/redirect
