### ISSUE TITLE
Can't login: This function has crashed

### ISSUE THREAD

**Issue by jpfeuffer** [znck/grammarly#302]
```
An unhandled error in the function code triggered the following message:

Error - Invalid scheme: null

Stack trace
Error: Invalid scheme: null
    at validate (/var/task/redirect.js:36:35)
    at Runtime.exports.handler (/var/task/redirect.js:16:5)
    at Runtime.handleOnceNonStreaming (/var/runtime/Runtime.js:73:25)
```

**Comment by kamil-akbar** [comment]
I am having the same issue.

**Comment by wham** [comment]
I can reproduce this when using the hosted VS Code in GitHub Codespaces - `*.github.dev`. Works correctly with VS Code desktop.

**Comment by jpfeuffer** [comment]
yes mine was hosted. gitpod or github.dev

**Comment by rogerbramon** [comment]
Steps to reproduce:
1. Open this repo with github.dev: https://github.dev/znck/grammarly
2. Install Grammarly for VS Code extension
3. Run `Grammarly: Login` command on `cmd shift P` panel.
4. Login to Grammarly and click `Continue` on Grammarly auth page
5. On the Netlify function you'll get the error.

As far as I can see, it's because the Uri coded on `state` param does not have the expected form. It looks like:
`https://github.dev/extension-auth-callback?state=<extension-internal-uri-state>`

It doesn't contain the expected params on redirect.jsL16:
```js
validate(
      url.searchParams.get('vscode-scheme'),
      url.searchParams.get('vscode-authority'),
      url.searchParams.get('vscode-path'),
    )
```

Hope that helps @znck. How we should proceed?
