### ISSUE TITLE
`Connection status: error` for .md files

### ISSUE THREAD

**Issue by varunkumar** [znck/grammarly#333]
Unable to use the extension with `.md` files. Getting the following message

> Your Grammarly account is used for this file. 
> Connection status: error
> Restart now?

It repeatedly fails on restarts as well.

**Comment by almarquis** [comment]
I'm having the same challenge.

**Comment by varunkumar** [comment]
@znck any help on this?

**Comment by Maximinodotpy** [comment]
Me too, I tried Reinstalling it and logging into my Grammarly account but it did not work.

**Comment by DanielRunningen** [comment]
Here's the stack trace after trying to add `**/*md` to the list of file types.

```
node:internal/deps/undici/undici:11413
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from /home/me/.vscode/extensions/znck.grammarly-0.23.15/dist/server/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at URL.onParseError (node:internal/url:566:9)
      at new URL (node:internal/url:646:5)
      at new Request (node:internal/deps/undici/undici:7002:25)
      at fetch2 (node:internal/deps/undici/undici:10554:25)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:248:25)
      at /home/me/.vscode/extensions/znck.grammarly-0.23.15/dist/server/index.node.js:34:77331
      at /home/me/.vscode/extensions/znck.grammarly-0.23.15/dist/server/index.node.js:34:77551
      at new Promise (<anonymous>) {
    input: '/home/me/.vscode/extensions/znck.grammarly-0.23.15/dist/server/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.15.0
[Error - 11:13:05 AM] Connection to server got closed. Server will not be restarted.
```
