### ISSUE TITLE
Grammarly login shows an error

### ISSUE THREAD

**Issue by martinszeltins** [znck/grammarly#352]
I am following the instructions to log into Grammarly on VSCode but I am getting this error (Linux, Ubuntu 20.04)

![image](https://user-images.githubusercontent.com/34019878/222063110-397d860c-f507-41b1-be2e-3291daec89ae.png)

> Request $/handleOAuthCallbackUri failed with message: Minified error #8: See https://developer.grammarly.com/docs/error-explainer...

````
Grammarly account or premium

Run grammarly.login or Grammarly: Login / Connect your account command to connect your Grammarly account.
Run grammarly.logout or Grammarly: Log out to disconnect your account.
````

I ran `grammarly.login` then I was redirected to the Grammarly login page and then I clicked on the "Continue" button and then this error showed up in my VSCode.

**Comment by gfraiteur** [comment]
Same here.

**Comment by nicofranzp** [comment]
+1 ... MacOS: `shift+cmd+p`, select "Login/connect to your account", follow the instructions and get the error.

**Comment by slyons** [comment]
Nothing in the output console, either

**Comment by ZhijieFan** [comment]
Same here.

**Comment by tmogoa** [comment]
Same here.

**Comment by tmogoa** [comment]
> Same here.

I switched to the pre-release version and now it works.

**Comment by chienhsiang-hung** [comment]
> > Same here.
> 
> I switched to the pre-release version and now it works.

Tried pre-release. No error this time but still not logged in.

**Comment by Raaghu** [comment]
+1

**Comment by gragusa** [comment]
With the pre-release version, I get the following error when I `shift+p - Check Text`

```
Ready!
[Error - 5:03:50 PM] Server initialization failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\DummyUser\.vscode\extensions\node_modules\.pnpm\vscode-jsonrpc@6.0.0\node_modules\vscode-jsonrpc\lib\common\connection.js:1044:27)
    at Object.dispose (c:\Users\DummyUser\.vscode\extensions\node_modules\.pnpm\vscode-languageclient@7.0.0\node_modules\vscode-languageclient\lib\common\client.js:73:35)
    at c:\Users\DummyUser\.vscode\extensions\node_modules\.pnpm\vscode-languageclient@7.0.0\node_modules\vscode-languageclient\lib\common\client.js:2320:28
[Error - 5:03:50 PM] Starting client failed
Error: Connection got disposed.
    at Object.dispose (c:\Users\DummyUser\.vscode\extensions\node_modules\.pnpm\vscode-jsonrpc@6.0.0\node_modules\vscode-jsonrpc\lib\common\connection.js:1044:27)
    at Object.dispose (c:\Users\DummyUser\.vscode\extensions\node_modules\.pnpm\vscode-languageclient@7.0.0\node_modules\vscode-languageclient\lib\common\client.js:73:35)
    at c:\Users\DummyUser\.vscode\extensions\node_modules\.pnpm\vscode-languageclient@7.0.0\node_modules\vscode-languageclient\lib\common\client.js:2320:28
```

I cannot login and cannot check text. This happens on a fresh copy of VSCode with only this extension installed.

**Comment by qwezey** [comment]
I'm facing the same issue

**Comment by bajtos** [comment]
Same problem here. When I open the URL from the error reported by the VS Code Extension,  Grammarly website shows this:

```
Invalid oauth callback url: vscode://znck.grammarly/auth/callback?windowId=1
```

<img width="770" alt="Screenshot 2023-03-14 at 10 58 43" src="https://user-images.githubusercontent.com/1140553/224964959-a8d337c1-7499-4e57-8f00-5d17f1ddf696.png">

**Comment by rahji** [comment]
This is the same as closed issue #323 . It seems to still be an issue.

**Comment by spydx** [comment]
I can confirm that switching to pre-release fixes the issue.

**Comment by Jimmy-Z** [comment]
Yeah, I'm also having this issue.

**Comment by MahdiNazemi** [comment]
> This is the same as closed issue #323 . It seems to still be an issue.

That issue is about getting Error #7. Most people here seem to get Error #8:
```
Invalid oauth callback url: vscode://znck.grammarly/auth/callback?windowId=1
```

**Comment by MahdiNazemi** [comment]
It looks like [Grammarly has updated its APIs](https://developer.grammarly.com/docs/changelog/migrate). I suspect this causes the login error.

One of the changes is
> The `oauth` option is now specified at the top level as `oauthRedirectUri`.

**Comment by rellyrell24** [comment]
Not sure if anyone is working on this, but I made a [branch](https://github.com/JLG-Technology-LLC/grammarly/tree/jlgtechnology/issue352/grammarly-login-issue) with a possible implementation for updating Grammarly SDK to 2.x in hopes of solving this issue and possibly others.

**Comment by dqbd** [comment]
Linking a useful workaround found by @crmelchior in a different (duplicate?) issue:

https://github.com/znck/grammarly/issues/350#issuecomment-1483848906

After switching to 0.18.0, successfully logging in and switching back to release version, I'm still logged in and everything seems to work fine.
