### ISSUE TITLE
Bug: Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by Neilblaze** [znck/grammarly#356]
Getting this error log:

```sh
TypeError: Cannot read properties of undefined (reading 'apply')
    at he.<computed> (c:\Users\neilb\.vscode\extensions\znck.grammarly-0.22.1\dist\server\index.node.js:34:72529)
    at wasm://wasm/0019b3fa:wasm-function[227]:0x22d49
    at wasm://wasm/0019b3fa:wasm-function[384]:0x46717
    at wasm://wasm/000ad4a6:wasm-function[214]:0x24793
    at d._ts_parser_parse_wasm (c:\Users\neilb\.vscode\extensions\znck.grammarly-0.22.1\dist\server\index.node.js:34:81471)
    at r.parse (c:\Users\neilb\.vscode\extensions\znck.grammarly-0.22.1\dist\server\index.node.js:34:95337)
    at Qd.d3 (c:\Users\neilb\.vscode\extensions\znck.grammarly-0.22.1\dist\server\index.node.js:64:6941)
    at async c:\Users\neilb\.vscode\extensions\znck.grammarly-0.22.1\dist\server\index.node.js:64:5453
    at async Qd.isReady (c:\Users\neilb\.vscode\extensions\znck.grammarly-0.22.1\dist\server\index.node.js:64:5540)
    at async c:\Users\neilb\.vscode\extensions\znck.grammarly-0.22.1\dist\server\index.node.js:64:4177
[Error - 6:57:49 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by Neilblaze** [comment]
Also getting this error msg:

![image](https://user-images.githubusercontent.com/48355572/229133735-846b5c23-1639-4dfb-918b-271544043938.png)

**Comment by stevenj** [comment]
I am seeing this as well.
