### ISSUE TITLE
Failed to parse URL... Invalid URL...

### ISSUE THREAD

**Issue by peter-kehl** [znck/grammarly#388]
Thank you for Grammarly for VS Code.

Installed `v0.22.1` on the current Manjaro (stable Arch Linux, x86 64bit); current VS Code as it comes from Manjaro/Arch repository. No configuration for this extension. Restarted VS Code, opened a simple `README.md`, and got the below error in a side panel:

```
Ready!
Initialized!
open file:///share/pkehl/GIT/wdav-hash-rs/README.md
create text checking session for "file:///share/pkehl/GIT/wdav-hash-rs/README.md" with {
  "documentDialect": "auto-text",
  "documentDomain": "general",
  "suggestions": {
    "ConjunctionAtStartOfSentence": false,
    "Fluency": true,
    "InformalPronounsAcademic": false,
    "MissingSpaces": true,
    "NounStrings": true,
    "NumbersBeginningSentences": true,
    "NumbersZeroThroughTen": true,
    "OxfordComma": false,
    "PassiveVoice": false,
    "PersonFirstLanguage": true,
    "PossiblyBiasedLanguageAgeRelated": true,
    "PossiblyBiasedLanguageDisabilityRelated": true,
    "PossiblyBiasedLanguageFamilyRelated": true,
    "PossiblyBiasedLanguageGenderRelated": true,
    "PossiblyBiasedLanguageHumanRights": true,
    "PossiblyBiasedLanguageHumanRightsRelated": true,
    "PossiblyBiasedLanguageLgbtqiaRelated": true,
    "PossiblyBiasedLanguageRaceEthnicityRelated": true,
    "PossiblyPoliticallyIncorrectLanguage": true,
    "PrepositionAtTheEndOfSentence": false,
    "PunctuationWithQuotation": true,
    "ReadabilityFillerwords": true,
    "ReadabilityTransforms": true,
    "SentenceVariety": true,
    "SpacesSurroundingSlash": true,
    "SplitInfinitive": true,
    "StylisticFragments": false,
    "UnnecessaryEllipses": true,
    "Variety": true,
    "Vocabulary": true
  }
} 
node:internal/deps/undici/undici:11413
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from /home/pkehl/.vscode/extensions/znck.grammarly-0.22.1/dist/server/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at URL.onParseError (node:internal/url:566:9)
      at new URL (node:internal/url:646:5)
      at new Request (node:internal/deps/undici/undici:7002:25)
      at fetch2 (node:internal/deps/undici/undici:10554:25)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:248:25)
      at /home/pkehl/.vscode/extensions/znck.grammarly-0.22.1/dist/server/index.node.js:34:77333
      at /home/pkehl/.vscode/extensions/znck.grammarly-0.22.1/dist/server/index.node.js:34:77553
      at new Promise (<anonymous>) {
    input: '/home/pkehl/.vscode/extensions/znck.grammarly-0.22.1/dist/server/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.15.0
[Error - 07:57:02] Connection to server got closed. Server will not be restarted.
[Error - 07:57:02] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/pkehl/.vscode/extensions/znck.grammarly-0.22.1/dist/extension/index.node.js:30:4048)
	at Object.dispose (/home/pkehl/.vscode/extensions/znck.grammarly-0.22.1/dist/extension/index.node.js:35:9520)
	at os.handleConnectionClosed (/home/pkehl/.vscode/extensions/znck.grammarly-0.22.1/dist/extension/index.node.js:37:9054)
	at os.handleConnectionClosed (/home/pkehl/.vscode/extensions/znck.grammarly-0.22.1/dist/extension/index.node.js:40:12095)
	at r (/home/pkehl/.vscode/extensions/znck.grammarly-0.22.1/dist/extension/index.node.js:37:8736)
	at Zs.invoke (/home/pkehl/.vscode/extensions/znck.grammarly-0.22.1/dist/extension/index.node.js:3:9583)
	at Kr.fire (/home/pkehl/.vscode/extensions/znck.grammarly-0.22.1/dist/extension/index.node.js:3:10348)
	at Rt (/home/pkehl/.vscode/extensions/znck.grammarly-0.22.1/dist/extension/index.node.js:4:10852)
	at Zs.invoke (/home/pkehl/.vscode/extensions/znck.grammarly-0.22.1/dist/extension/index.node.js:3:9583)
	at Kr.fire (/home/pkehl/.vscode/extensions/znck.grammarly-0.22.1/dist/extension/index.node.js:3:10348)
	at wo.fireClose (/home/pkehl/.vscode/extensions/znck.grammarly-0.22.1/dist/extension/index.node.js:3:12622)
	at ChildProcess.<anonymous> (/home/pkehl/.vscode/extensions/znck.grammarly-0.22.1/dist/extension/index.node.js:30:11847)
	at ChildProcess.emit (node:events:525:35)
	at maybeClose (node:internal/child_process:1091:16)
	at Socket.<anonymous> (node:internal/child_process:449:11)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:322:12)
```

```
Version: 1.82.2
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:51:20.981Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.5.1-1-MANJARO
```

Please help.

**Comment by peter-kehl** [comment]
I have `npm` installed NOT from Manjaro/Arch, but directly from NPM.

```
npm --version
9.8.0
```

**Comment by peter-kehl** [comment]
Similar/same error when I switched to the current pre-release `v0.23.15`:
```
Ready!
Initializing...
Initialized!
open file:///share/pkehl/GIT/wdav-hash-rs/README.md
create text checking session for "file:///share/pkehl/GIT/wdav-hash-rs/README.md" with {
  "documentDialect": "american",
  "documentDomain": "general",
  "suggestionCategories": {
    "conjugationAtStartOfSentence": "off",
    "fluency": "on",
    "informalPronounsAcademic": "off",
    "missingSpaces": "on",
    "nounStrings": "on",
    "numbersBeginningSentences": "on",
    "numbersZeroThroughTen": "on",
    "oxfordComma": "off",
    "passiveVoice": "off",
    "personFirstLanguage": "on",
    "possiblyBiasedLanguageAgeRelated": "on",
    "possiblyBiasedLanguageDisabilityRelated": "on",
    "possiblyBiasedLanguageFamilyRelated": "on",
    "possiblyBiasedLanguageGenderRelated": "on",
    "possiblyBiasedLanguageHumanRights": "on",
    "possiblyBiasedLanguageHumanRightsRelated": "on",
    "possiblyBiasedLanguageLGBTQIARelated": "on",
    "possiblyBiasedLanguageRaceEthnicityRelated": "on",
    "possiblyPoliticallyIncorrectLanguage": "on",
    "prepositionAtTheEndOfSentence": "off",
    "punctuationWithQuotation": "on",
    "readabilityFillerWords": "on",
    "readabilityTransforms": "on",
    "sentenceVariety": "on",
    "spacesSurroundingSlash": "on",
    "splitInfinitive": "on",
    "stylisticFragments": "off",
    "unnecessaryEllipses": "off",
    "variety": "on",
    "vocabulary": "on"
  }
} 
text checking session for "file:///share/pkehl/GIT/wdav-hash-rs/README.md" is ready
node:internal/deps/undici/undici:11413
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from /home/pkehl/.vscode/extensions/znck.grammarly-0.23.15/dist/server/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at URL.onParseError (node:internal/url:566:9)
      at new URL (node:internal/url:646:5)
      at new Request (node:internal/deps/undici/undici:7002:25)
      at fetch2 (node:internal/deps/undici/undici:10554:25)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:248:25)
      at /home/pkehl/.vscode/extensions/znck.grammarly-0.23.15/dist/server/index.node.js:34:77331
      at /home/pkehl/.vscode/extensions/znck.grammarly-0.23.15/dist/server/index.node.js:34:77551
      at new Promise (<anonymous>) {
    input: '/home/pkehl/.vscode/extensions/znck.grammarly-0.23.15/dist/server/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.15.0
[Error - 08:04:35] Connection to server got closed. Server will not be restarted.
```

**Comment by Nicceboy** [comment]
Might be related to this. https://github.com/znck/grammarly/issues/380

**Comment by peter-kehl** [comment]
Duplicate of #380. Thank you.
